apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-frontend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/itamardavideliyahu-beep/weather-helm-infra
    targetRevision: main
    path: weather-helm-infra/charts/weather-frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: weather
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
